### ISSUE TITLE
Meeting Minutes and Agenda

### ISSUE THREAD

**Issue by rtmccune** [NCRoadNetworks/PiCamML#10]
This will be where meeting minutes and future agendas are recorded for monthly update meetings.

**Comment by rtmccune** [comment]
09/14/2022

[Meeting Presentation](https://docs.google.com/presentation/d/14CdU0BrOYtS2nq9T4jVq5ST27VYb1Q4weq0wNitV3MI/edit?usp=sharing)

**Comment by anardek** [comment]
- moving forward, we're not going to have these minutes as issues, but rather "discussions"
- Ryan is going to figure out how to move pycharm files to gitignore
