### ISSUE TITLE
map NCDOT locations

### ISSUE THREAD

**Issue by ebgoldstein** [NCRoadNetworks/PiCamML#13]
- develop a map with all locations from NCDOT email

**Comment by rtmccune** [comment]
@ebgoldstein @anardek  - I didn't receive the email with the locations. Could someone please forward the email?

**Comment by ebgoldstein** [comment]
~yes, i will~ - now done

**Comment by ebgoldstein** [comment]
this is now done.. @rtmccune can you drop a link or static map in here and then close the issue?

**Comment by rtmccune** [comment]
https://arcg.is/0aaTrP
