### ISSUE TITLE
Intro to doodler

### ISSUE THREAD

**Issue by ebgoldstein** [NCRoadNetworks/PiCamML#8]
- [x] get an understanding of doodler, adn how it works
- [x] look at existing doodled images (from Joe)

**Comment by rtmccune** [comment]
@ebgoldstein I'm receiving this error when I check the compute/segment button. Could you help me to understand how to resolve it?

![Image](https://user-images.githubusercontent.com/108094076/191809058-a87a18b5-35d7-4515-aa61-a8a2f3479d7e.png)

**Comment by ebgoldstein** [comment]
@rtmccune 
is this an M1 mac?
and what browser?

**Comment by rtmccune** [comment]
@ebgoldstein 
Yes, and I was in Chrome

MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
